blank_issues_enabled: true
contact_links:
  - name: Riot Channel - WildfirePy
    url: https://matrix.to/#/!jWUOIxirCHymPQkpXb:matrix.org?via=matrix.org
    about: Discussion on the development of WildfirePy
